const app=document.querySelector('#app'),modal=document.querySelector('#modal'),modalContent=document.querySelector('#modalContent');
const DAYS=['Понедельник','Вторник','Среда','Четверг','Пятница','Суббота','Воскресенье'];
const SLOTS=[['breakfast','Завтрак'],['lunch','Обед'],['snack','Перекус'],['dinner','Ужин']];
const DEFAULT_TARGET={kcal:1750,protein:130,fat:60,carbs:165};
const raw=JSON.parse(localStorage.getItem('mealState')||'{}');
function uid(){return 'p'+Math.random().toString(36).slice(2,9)}
function makeProfile(name='Я',target=DEFAULT_TARGET,legacy={}){return {id:uid(),name,target:{...DEFAULT_TARGET,...target},plan:legacy.plan||{},favorites:legacy.favorites||[],weight:'',note:''}}
const state=raw;
state.recipeIngredients??={};state.shopping??={};state.cookingDone??={};state.view??='today';state.combineHousehold??=true;
if(!Array.isArray(state.profiles)||!state.profiles.length){state.profiles=[makeProfile('Я',DEFAULT_TARGET,{plan:state.plan||{},favorites:state.favorites||[]})]}
state.activeProfileId??=state.profiles[0].id;
state.householdProfileIds??=state.profiles.map(p=>p.id);
delete state.plan;delete state.favorites;
const save=()=>localStorage.setItem('mealState',JSON.stringify(state));save();
const profile=()=>state.profiles.find(p=>p.id===state.activeProfileId)||state.profiles[0];
const participants=()=>state.combineHousehold?state.profiles.filter(p=>state.householdProfileIds.includes(p.id)):[profile()];
const target=()=>profile().target||DEFAULT_TARGET;
const dish=id=>DISHES.find(d=>d.id===id);
const totals=ids=>ids.map(dish).filter(Boolean).reduce((a,d)=>({kcal:a.kcal+d.kcal,protein:a.protein+d.protein,fat:a.fat+d.fat,carbs:a.carbs+d.carbs}),{kcal:0,protein:0,fat:0,carbs:0});
const currentDay=()=>DAYS[(new Date().getDay()+6)%7];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function macro(t,label,key){return `<div class="macro"><b>${Math.round(t[key])}</b><span>${label}</span></div>`}
function recipeIngredients(id){return state.recipeIngredients[id]||RECIPE_DETAILS[id]?.ingredients||[]}
function ingredientText(x){return `${esc(x.name)} — ${x.qty} ${x.unit||'г'}`}

function mealRow(day,key,label){const p=profile(),d=dish((p.plan[day]||{})[key]);if(!d)return `<div class="slot empty-slot" onclick="chooseMeal('${day}','${key}')"><span>${label}: <b>выбрать блюдо</b></span><button>＋</button></div>`;return `<div class="slot meal-slot"><button class="meal-open" onclick="openDish('${d.id}')"><span><small>${label}</small><b>${esc(d.name)}</b><em>${d.kcal} ккал · Б ${d.protein}</em></span></button><button class="replace-btn" onclick="chooseMeal('${day}','${key}')">заменить</button></div>`}
function renderToday(){const p=profile(),day=currentDay(),pp=p.plan[day]||{},t=totals(SLOTS.map(([k])=>pp[k]).filter(Boolean)),tar=target();app.innerHTML=`<section class="hero"><span class="eyebrow">${esc(p.name)} · ${day}</span><h2>${t.kcal} / ${tar.kcal} ккал</h2><div class="macro-grid">${macro(t,'ккал','kcal')}${macro(t,'белок','protein')}${macro(t,'жиры','fat')}${macro(t,'углеводы','carbs')}</div><div class="progress"><i style="width:${Math.min(100,t.kcal/tar.kcal*100)}%"></i></div></section><section class="section"><h2>Сегодня</h2>${SLOTS.map(([k,l])=>mealRow(day,k,l)).join('')}</section><section class="section"><button class="btn" onclick="randomizeDay('${day}')">Собрать день автоматически</button></section>`}
function cardHTML(d){return `<div class="card dish-card" onclick="openDish('${d.id}')"><div><div class="dish-id">${d.id} · ${d.category}</div><div class="dish-title">${esc(d.name)}</div><div class="meta">${d.minutes} мин · Б ${d.protein} г · ${d.tags.slice(0,3).join(' · ')}</div></div><div><div class="kcal">${d.kcal}</div><div class="meta">ккал</div></div></div>`}
function renderLibrary(){const p=profile();app.innerHTML=`<input id="search" class="search" placeholder="Найти блюдо или ингредиент"><div class="chips" id="cats">${['Все','Завтрак','Основное','Перекус','Аварийное','❤️'].map((x,i)=>`<button class="chip ${i===0?'active':''}" data-cat="${x}">${x}</button>`).join('')}</div><div id="dishList"></div>`;let cat='Все';const draw=()=>{const q=document.querySelector('#search').value.toLowerCase();const arr=DISHES.filter(d=>(cat==='Все'||d.category===cat||(cat==='❤️'&&p.favorites.includes(d.id)))&&(d.name+' '+d.ingredients.join(' ')+' '+d.tags.join(' ')).toLowerCase().includes(q));document.querySelector('#dishList').innerHTML=arr.map(cardHTML).join('')||'<div class="empty">Ничего не найдено.</div>'};document.querySelector('#search').oninput=draw;document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{cat=b.dataset.cat;document.querySelectorAll('[data-cat]').forEach(x=>x.classList.toggle('active',x===b));draw()});draw()}
function openDish(id){const d=dish(id),r=RECIPE_DETAILS[id],ings=recipeIngredients(id),p=profile();modalContent.innerHTML=`<span class="eyebrow">${d.id} · ${d.category}</span><h2 style="padding-right:44px">${esc(d.name)}</h2><div class="macro-grid">${[['ккал',d.kcal],['Б',d.protein],['Ж',d.fat],['У',d.carbs]].map(x=>`<div class="macro"><b>${x[1]}</b><span>${x[0]}</span></div>`).join('')}</div><section class="section"><div class="day-head"><h3>Ингредиенты · 1 порция</h3><button class="chip" onclick="editIngredients('${id}')">✎ изменить</button></div><ul class="ingredient-list">${ings.map(x=>`<li>${ingredientText(x)}</li>`).join('')}</ul><p class="tiny-note">Крупы/паста/картофель указаны в готовом виде; мясо и рыба преимущественно в сыром.</p></section><section class="section"><h3>Приготовление</h3><p class="note">${esc(r.steps)}</p></section><section class="section"><h3>Хранение и заготовка</h3><p class="note">${esc(r.storage||'Ориентируйтесь на самый скоропортящийся компонент.')}</p></section>${r.replacements?`<section class="section"><h3>Замены</h3><p class="note">${esc(r.replacements)}</p></section>`:''}<div class="row"><button class="btn" onclick="toggleFavorite('${id}')">${p.favorites.includes(id)?'♥ В любимых':'♡ В любимое'}</button><button class="btn secondary" onclick="addToToday('${id}')">Добавить сегодня</button></div>`;modal.classList.remove('hidden')}
function editIngredients(id){window._editingIngredients=recipeIngredients(id).map(x=>({...x}));const draw=()=>{modalContent.innerHTML=`<h2>Граммовки · ${esc(dish(id).name)}</h2><p class="note">Количество на 1 порцию. Изменения общие для всех профилей на этом устройстве.</p><div>${window._editingIngredients.map((x,i)=>`<div class="ingredient-edit-row"><input value="${esc(x.name)}" oninput="_editingIngredients[${i}].name=this.value"><input type="number" min="0" step="1" value="${x.qty}" oninput="_editingIngredients[${i}].qty=Number(this.value)"><select onchange="_editingIngredients[${i}].unit=this.value">${['г','мл','шт','ст.л.','ч.л.','банка','уп.'].map(u=>`<option ${x.unit===u?'selected':''}>${u}</option>`).join('')}</select><button class="remove-ing" onclick="_editingIngredients.splice(${i},1);editIngredients('${id}')">×</button></div>`).join('')}</div><div class="week-actions"><button class="btn secondary" onclick="_editingIngredients.push({name:'',qty:0,unit:'г'});editIngredients('${id}')">＋ ингредиент</button><button class="btn" onclick="state.recipeIngredients['${id}']=_editingIngredients.filter(x=>x.name.trim());save();openDish('${id}')">Сохранить</button></div>`};draw()}
function toggleFavorite(id){const p=profile();p.favorites=p.favorites.includes(id)?p.favorites.filter(x=>x!==id):[...p.favorites,id];save();openDish(id)}
function addToToday(id){const p=profile(),d=dish(id),key=d.category==='Завтрак'?'breakfast':d.category==='Перекус'?'snack':'dinner';p.plan[currentDay()]??={};p.plan[currentDay()][key]=id;save();modal.classList.add('hidden');render()}

function renderWeek(){const p=profile(),ts=DAYS.map(day=>totals(SLOTS.map(([k])=>(p.plan[day]||{})[k]).filter(Boolean))),filled=ts.filter(t=>t.kcal>0),avg=filled.length?Math.round(filled.reduce((a,t)=>a+t.kcal,0)/filled.length):0;app.innerHTML=`<section><h2>Неделя · ${esc(p.name)}</h2><div class="week-actions"><button class="btn" onclick="randomizeWeek()">Составить экономную неделю</button><button class="btn secondary" onclick="clearWeek()">Очистить</button></div>${filled.length?`<div class="week-summary">Среднее: <b>${avg} ккал/день</b> · ${filled.length}/7 дней</div>`:''}<p class="note">Автоплан ограничивает число баз: обычно 2 белка + 2 гарнира на неделю, а разнообразие создают соусы и сборка.</p>${DAYS.map(day=>{const pp=p.plan[day]||{},t=totals(SLOTS.map(([k])=>pp[k]).filter(Boolean));return `<div class="day"><div class="day-head"><b>${day}</b><span class="meta">${t.kcal} ккал · Б ${t.protein}</span></div><div class="slots">${SLOTS.map(([k,l])=>mealRow(day,k,l)).join('')}</div></div>`}).join('')}</section>`}
function clearWeek(){profile().plan={};state.cookingDone={};save();render()}
function chooseMeal(day,key){const desired=key==='breakfast'?'Завтрак':key==='snack'?'Перекус':'Основное';const arr=DISHES.filter(d=>d.category===desired||(key!=='breakfast'&&key!=='snack'&&d.category==='Аварийное'));const draw=q=>arr.filter(d=>(d.name+' '+d.ingredients.join(' ')).toLowerCase().includes(q.toLowerCase())).map(d=>`<div class="card dish-card picker-row"><button class="picker-info" onclick="openDish('${d.id}')"><div class="dish-title">${esc(d.name)}</div><div class="meta">${d.kcal} ккал · Б ${d.protein}</div></button><button class="pick-btn" onclick="setMeal('${day}','${key}','${d.id}')">выбрать</button></div>`).join('');modalContent.innerHTML=`<h2>Выбрать: ${SLOTS.find(s=>s[0]===key)[1]}</h2><input class="search" id="pickerSearch" placeholder="Поиск"><div id="pickerList">${draw('')}</div>`;modal.classList.remove('hidden');document.querySelector('#pickerSearch').oninput=e=>document.querySelector('#pickerList').innerHTML=draw(e.target.value)}
function setMeal(day,key,id){const p=profile();p.plan[day]??={};p.plan[day][key]=id;state.cookingDone={};save();modal.classList.add('hidden');render()}
function randomizeDay(day){const p=profile(),tar=target(),b=DISHES.filter(d=>d.category==='Завтрак'),m=DISHES.filter(d=>d.category==='Основное'),sn=DISHES.filter(d=>d.category==='Перекус');let best,bestScore=1e9;for(let i=0;i<700;i++){const pp={breakfast:b[Math.random()*b.length|0].id,lunch:m[Math.random()*m.length|0].id,snack:sn[Math.random()*sn.length|0].id,dinner:m[Math.random()*m.length|0].id},t=totals(Object.values(pp)),score=Math.abs(t.kcal-tar.kcal)*1.2+Math.abs(t.protein-tar.protein)*4+(pp.lunch===pp.dinner?100:0);if(score<bestScore){bestScore=score;best=pp}}p.plan[day]=best;state.cookingDone={};save();render()}

const proteinFamily=d=>{const s=(d.tags.join(' ')+' '+d.ingredients.join(' ')).toLowerCase();if(s.includes('куриц'))return'Курица';if(s.includes('индей'))return'Индейка';if(s.includes('говя'))return'Говядина';if(s.includes('лосос'))return'Лосось';if(s.includes('тунец'))return'Тунец';if(s.includes('рыба'))return'Белая рыба';if(s.includes('кревет'))return'Креветки';if(s.includes('фалафель')||s.includes('чечев'))return'Бобовые';return'Другое'};
const carbFamily=d=>{const s=d.ingredients.join(' ').toLowerCase();if(s.includes('рис'))return'Рис';if(s.includes('картоф'))return'Картофель';if(s.includes('паста')||s.includes('лазан'))return'Паста';if(s.includes('булгур'))return'Булгур';if(s.includes('удон'))return'Удон';if(s.includes('пита')||s.includes('тортиль'))return'Лепёшки';return'Другое'};
const WEEK_TEMPLATES=[
 {proteins:['Курица','Индейка'],carbs:['Рис','Картофель','Паста'],label:'курица + индейка'},
 {proteins:['Курица','Говядина'],carbs:['Рис','Картофель','Паста'],label:'курица + говядина'},
 {proteins:['Курица','Лосось'],carbs:['Рис','Картофель','Булгур'],label:'курица + рыба'},
 {proteins:['Говядина','Индейка'],carbs:['Рис','Картофель','Паста'],label:'говядина + индейка'}
];
function randomizeWeek(){const p=profile(),tar=target(),b=DISHES.filter(d=>d.category==='Завтрак'),sn=DISHES.filter(d=>d.category==='Перекус'),allM=DISHES.filter(d=>d.category==='Основное');const tpl=WEEK_TEMPLATES[Math.random()*WEEK_TEMPLATES.length|0];let mains=allM.filter(d=>tpl.proteins.includes(proteinFamily(d))&&tpl.carbs.includes(carbFamily(d)));if(mains.length<6)mains=allM.filter(d=>tpl.proteins.includes(proteinFamily(d)));
 const breakfastPool=[...b].sort(()=>Math.random()-.5).slice(0,4), snackPool=[...sn].sort(()=>Math.random()-.5).slice(0,4);const used={};
 DAYS.forEach((day,di)=>{let best,bestScore=1e9;for(let i=0;i<800;i++){const lunch=mains[Math.random()*mains.length|0],dinner=mains[Math.random()*mains.length|0],pp={breakfast:breakfastPool[di%breakfastPool.length].id,lunch:lunch.id,snack:snackPool[di%snackPool.length].id,dinner:dinner.id},t=totals(Object.values(pp));const repeat=(used[lunch.id]||0)*18+(used[dinner.id]||0)*18;const uniqueProtein=(proteinFamily(lunch)!==proteinFamily(dinner)?10:0);const score=Math.abs(t.kcal-tar.kcal)*1.2+Math.abs(t.protein-tar.protein)*4+repeat+(lunch.id===dinner.id?80:0)+uniqueProtein;if(score<bestScore){bestScore=score;best=pp}}p.plan[day]=best;[best.lunch,best.dinner].forEach(id=>used[id]=(used[id]||0)+1)});state.cookingDone={};save();render()}

function selectedPlans(){return participants().flatMap(p=>DAYS.flatMap(day=>Object.values(p.plan[day]||{}).map(id=>({profile:p,day,id})).filter(x=>x.id)))}
function shoppingItems(){const exact=new Map();selectedPlans().forEach(({id})=>recipeIngredients(id).forEach(x=>{const key=`${x.name}|${x.unit||'г'}`;exact.set(key,(exact.get(key)||0)+Number(x.qty||0))}));return [...exact.entries()].map(([key,qty])=>{const [name,unit]=key.split('|');return{name,unit,qty}}).filter(x=>x.qty>0).sort((a,b)=>a.name.localeCompare(b.name,'ru'))}
function householdToggleHTML(){return `<div class="household-toggle"><button class="chip ${!state.combineHousehold?'active':''}" onclick="state.combineHousehold=false;save();render()">${esc(profile().name)}</button><button class="chip ${state.combineHousehold?'active':''}" onclick="state.combineHousehold=true;save();render()">Все участники</button></div>`}
function renderShopping(){const items=shoppingItems();app.innerHTML=`<section><h2>Покупки</h2>${householdToggleHTML()}<p class="note">${state.combineHousehold?'Суммированы меню всех выбранных участников.':'Список только для текущего профиля.'}</p>${items.map(x=>{const key=`${x.name}|${x.unit}`;return `<label class="shop-row ${state.shopping[key]?'done':''}"><input type="checkbox" ${state.shopping[key]?'checked':''} onchange="toggleShop('${key.replace(/'/g,"\\'")}')"><span>${esc(x.name)} <b>${Math.round(x.qty*10)/10} ${x.unit}</b></span></label>`}).join('')||'<div class="empty">Сначала составьте меню.</div>'}</section>`}
function toggleShop(k){state.shopping[k]=!state.shopping[k];save();renderShopping()}

function normName(s){return s.toLowerCase().replace(/ё/g,'е')}
function prepGroup(name){const s=normName(name);if(/курин|курица/.test(s))return['protein','Курица'];if(/индей/.test(s))return['protein','Индейка'];if(/говя/.test(s))return['protein','Говядина'];if(/лосос/.test(s))return['fresh','Лосось'];if(/белая рыба/.test(s))return['fresh','Белая рыба'];if(/кревет/.test(s))return['fresh','Креветки'];if(/рис/.test(s))return['carb','Рис'];if(/картоф/.test(s))return['carb','Картофель'];if(/паста|лазан/.test(s))return['carb','Паста'];if(/булгур/.test(s))return['carb','Булгур'];if(/удон/.test(s))return['carb','Удон'];if(/брокколи|морковь|перец|овощ|кабач|баклаж|шпинат/.test(s))return['veg','Овощи'];return null}
function aggregatePrep(){const map=new Map();selectedPlans().forEach(({id})=>recipeIngredients(id).forEach(x=>{if((x.unit||'г')!=='г')return;const g=prepGroup(x.name);if(!g)return;const [type,label]=g,key=type+'|'+label;const z=map.get(key)||{type,label,qty:0,examples:new Set()};z.qty+=Number(x.qty||0);z.examples.add(dish(id)?.name||id);map.set(key,z)}));return [...map.values()]}
function cookingPlan(){const all=selectedPlans();if(!all.length)return[];const prep=aggregatePrep(),groups=[];const sunday=prep.filter(x=>x.type==='protein'||x.type==='carb'||x.type==='veg');const fresh=prep.filter(x=>x.type==='fresh');if(sunday.length)groups.push({title:'Воскресенье · базовая готовка',time:'около 90–120 мин',items:sunday.map(x=>({key:'base-'+x.label,label:`${x.label} · ${Math.round(x.qty)} г`,text:x.type==='protein'?`Приготовить нейтральной базой и разделить на порции. Вкус меняют соусы и сборка (${[...x.examples].slice(0,3).join(', ')}).`:x.type==='carb'?`Приготовить одной партией. Вес указан готового продукта; разложить по контейнерам.`:`Запечь/подготовить общую овощную базу, часть оставить свежей.`}))});if(fresh.length)groups.push({title:'Среда · свежие белки',time:'около 25–40 мин',items:fresh.map(x=>({key:'fresh-'+x.label,label:`${x.label} · ${Math.round(x.qty)} г`,text:'Готовить ближе к употреблению; при необходимости разделить на 2 небольшие партии.'}))});
 const daily=DAYS.map(day=>{const meals=participants().flatMap(p=>Object.values(p.plan[day]||{}).map(id=>({p,id,d:dish(id),r:RECIPE_DETAILS[id]})).filter(x=>x.id));const freshMeals=meals.filter(x=>x.r?.prepType==='fresh'||x.r?.prepType==='nocook'||x.r?.prepType==='daybefore');if(!freshMeals.length)return null;return {key:'day-'+day,label:day,text:freshMeals.map(x=>`${x.p.name}: ${x.d.name}`).join(' · ')}}).filter(Boolean);if(daily.length)groups.push({title:'По дням · только сборка и свежее',time:'5–20 мин',items:daily});return groups}
function renderCooking(){const groups=cookingPlan();app.innerHTML=`<section><h2>Готовка</h2>${householdToggleHTML()}<p class="note">Сначала готовятся общие базы крупными партиями. Разные блюда получаются за счёт соусов, свежих добавок и сборки, а не семи отдельных кастрюль.</p>${groups.length?groups.map(g=>`<div class="cook-block"><div class="day-head"><h3>${g.title}</h3><span class="meta">${g.time}</span></div>${g.items.map(x=>`<label class="cook-task ${state.cookingDone[x.key]?'done':''}"><input type="checkbox" ${state.cookingDone[x.key]?'checked':''} onchange="toggleCook('${x.key.replace(/'/g,"\\'")}')"><span><b>${esc(x.label)}</b><small>${esc(x.text)}</small></span></label>`).join('')}</div>`).join(''):'<div class="empty">Сначала составьте меню на неделю.</div>'}</section>`}
function toggleCook(k){state.cookingDone[k]=!state.cookingDone[k];save();renderCooking()}

function openProfiles(){modalContent.innerHTML=`<span class="eyebrow">Участники</span><h2>Профили питания</h2><p class="note">Пока профили хранятся на этом устройстве. Каждый имеет своё меню и цели; готовка и покупки могут объединяться.</p><div>${state.profiles.map(p=>`<div class="profile-card ${p.id===state.activeProfileId?'active':''}"><button class="profile-main" onclick="switchProfile('${p.id}')"><b>${esc(p.name)}</b><small>${p.target.kcal} ккал · Б ${p.target.protein} г</small></button><button class="replace-btn" onclick="editProfile('${p.id}')">изменить</button></div>`).join('')}</div><button class="btn" onclick="editProfile('new')">＋ Добавить участника</button><section class="section"><h3>Общая готовка</h3>${state.profiles.map(p=>`<label class="shop-row"><input type="checkbox" ${state.householdProfileIds.includes(p.id)?'checked':''} onchange="toggleHouseholdProfile('${p.id}')"><span>${esc(p.name)}</span></label>`).join('')}</section>`;modal.classList.remove('hidden')}
function switchProfile(id){state.activeProfileId=id;save();modal.classList.add('hidden');render();updateProfileButton()}
function toggleHouseholdProfile(id){state.householdProfileIds=state.householdProfileIds.includes(id)?state.householdProfileIds.filter(x=>x!==id):[...state.householdProfileIds,id];if(!state.householdProfileIds.length)state.householdProfileIds=[state.activeProfileId];save();openProfiles()}
function editProfile(id){const existing=id==='new'?{id:null,name:'',target:{...DEFAULT_TARGET}}:state.profiles.find(p=>p.id===id);modalContent.innerHTML=`<h2>${id==='new'?'Новый участник':'Профиль'}</h2><label class="field">Имя<input id="pfName" value="${esc(existing.name)}"></label><div class="target-grid"><label class="field">ккал<input id="pfKcal" type="number" value="${existing.target.kcal}"></label><label class="field">Белок<input id="pfProtein" type="number" value="${existing.target.protein}"></label><label class="field">Жиры<input id="pfFat" type="number" value="${existing.target.fat}"></label><label class="field">Углеводы<input id="pfCarbs" type="number" value="${existing.target.carbs}"></label></div><button class="btn" onclick="saveProfile('${id}')">Сохранить</button>${id!=='new'&&state.profiles.length>1?`<button class="btn secondary danger" onclick="deleteProfile('${id}')">Удалить профиль</button>`:''}<p class="tiny-note">Для настоящей учётной записи с входом на разных телефонах понадобится серверная авторизация. Структура профилей уже отделена от общей базы рецептов, поэтому её можно подключить позже без переделки меню.</p>`}
function saveProfile(id){const t={kcal:+pfKcal.value||1750,protein:+pfProtein.value||130,fat:+pfFat.value||60,carbs:+pfCarbs.value||165},name=pfName.value.trim()||'Участник';if(id==='new'){const p=makeProfile(name,t);state.profiles.push(p);state.householdProfileIds.push(p.id);state.activeProfileId=p.id}else{const p=state.profiles.find(x=>x.id===id);p.name=name;p.target=t}save();modal.classList.add('hidden');updateProfileButton();render()}
function deleteProfile(id){state.profiles=state.profiles.filter(p=>p.id!==id);state.householdProfileIds=state.householdProfileIds.filter(x=>x!==id);if(state.activeProfileId===id)state.activeProfileId=state.profiles[0].id;save();modal.classList.add('hidden');updateProfileButton();render()}
function updateProfileButton(){const b=document.querySelector('#profileBtn');if(b)b.textContent=(profile().name||'Я').slice(0,2).toUpperCase()}

function render(){document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));({today:renderToday,library:renderLibrary,week:renderWeek,cooking:renderCooking,shopping:renderShopping}[state.view]||renderToday)();updateProfileButton()}
document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;save();render()});document.querySelector('#closeModal').onclick=()=>modal.classList.add('hidden');modal.onclick=e=>{if(e.target===modal)modal.classList.add('hidden')};document.querySelector('#profileBtn').onclick=openProfiles;
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;document.querySelector('#installBtn').classList.remove('hidden')});document.querySelector('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render();
