const app=document.querySelector('#app'),modal=document.querySelector('#modal'),modalContent=document.querySelector('#modalContent');
const state=JSON.parse(localStorage.getItem('mealState')||'{}');
state.favorites??=[];state.plan??={};state.shopping??={};state.recipeIngredients??={};state.view??='today';state.cookingDone??={};
const save=()=>localStorage.setItem('mealState',JSON.stringify(state));
const target={kcal:1750,protein:130,fat:60,carbs:165};
const days=['Понедельник','Вторник','Среда','Четверг','Пятница','Суббота','Воскресенье'];
const slots=[['breakfast','Завтрак'],['lunch','Обед'],['snack','Перекус'],['dinner','Ужин']];
const dish=id=>DISHES.find(d=>d.id===id);
const totals=ids=>ids.map(dish).filter(Boolean).reduce((a,d)=>({kcal:a.kcal+d.kcal,protein:a.protein+d.protein,fat:a.fat+d.fat,carbs:a.carbs+d.carbs}),{kcal:0,protein:0,fat:0,carbs:0});
const currentDay=()=>days[(new Date().getDay()+6)%7];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function macro(t,label,key){return `<div class="macro"><b>${Math.round(t[key])}</b><span>${label}</span></div>`}
function recipeIngredients(id){return state.recipeIngredients[id]||RECIPE_DETAILS[id]?.ingredients||[]}
function ingredientText(x){return `${esc(x.name)} — ${x.qty} ${x.unit||'г'}`}
function mealRow(day,key,label){const d=dish((state.plan[day]||{})[key]);if(!d)return `<div class="slot empty-slot" onclick="chooseMeal('${day}','${key}')"><span>${label}: <b>выбрать блюдо</b></span><button>＋</button></div>`;return `<div class="slot meal-slot"><button class="meal-open" onclick="openDish('${d.id}')"><span><small>${label}</small><b>${esc(d.name)}</b><em>${d.kcal} ккал · Б ${d.protein}</em></span></button><button class="replace-btn" onclick="chooseMeal('${day}','${key}')">заменить</button></div>`}
function renderToday(){const day=currentDay(),p=state.plan[day]||{},t=totals(slots.map(([k])=>p[k]).filter(Boolean));app.innerHTML=`<section class="hero"><span class="eyebrow">${day}</span><h2>${t.kcal} / ${target.kcal} ккал</h2><div class="macro-grid">${macro(t,'ккал','kcal')}${macro(t,'белок','protein')}${macro(t,'жиры','fat')}${macro(t,'углеводы','carbs')}</div><div class="progress"><i style="width:${Math.min(100,t.kcal/target.kcal*100)}%"></i></div></section><section class="section"><h2>Сегодня</h2>${slots.map(([k,l])=>mealRow(day,k,l)).join('')}</section><section class="section"><button class="btn" onclick="randomizeDay('${day}')">Собрать день автоматически</button></section>`}
function cardHTML(d){return `<div class="card dish-card" onclick="openDish('${d.id}')"><div><div class="dish-id">${d.id} · ${d.category}</div><div class="dish-title">${esc(d.name)}</div><div class="meta">${d.minutes} мин · Б ${d.protein} г · ${d.tags.slice(0,3).join(' · ')}</div></div><div><div class="kcal">${d.kcal}</div><div class="meta">ккал</div></div></div>`}
function renderLibrary(){app.innerHTML=`<input id="search" class="search" placeholder="Найти блюдо или ингредиент"><div class="chips" id="cats">${['Все','Завтрак','Основное','Перекус','Аварийное','❤️'].map((x,i)=>`<button class="chip ${i===0?'active':''}" data-cat="${x}">${x}</button>`).join('')}</div><div id="dishList"></div>`;let cat='Все';const draw=()=>{const q=document.querySelector('#search').value.toLowerCase();const arr=DISHES.filter(d=>(cat==='Все'||d.category===cat||(cat==='❤️'&&state.favorites.includes(d.id)))&&(d.name+' '+d.ingredients.join(' ')+' '+d.tags.join(' ')).toLowerCase().includes(q));document.querySelector('#dishList').innerHTML=arr.map(cardHTML).join('')||'<div class="empty">Ничего не найдено.</div>'};document.querySelector('#search').oninput=draw;document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{cat=b.dataset.cat;document.querySelectorAll('[data-cat]').forEach(x=>x.classList.toggle('active',x===b));draw()});draw()}
function openDish(id){const d=dish(id),r=RECIPE_DETAILS[id],ings=recipeIngredients(id);modalContent.innerHTML=`<span class="eyebrow">${d.id} · ${d.category}</span><h2 style="padding-right:44px">${esc(d.name)}</h2><div class="macro-grid">${[['ккал',d.kcal],['Б',d.protein],['Ж',d.fat],['У',d.carbs]].map(x=>`<div class="macro"><b>${x[1]}</b><span>${x[0]}</span></div>`).join('')}</div><section class="section"><div class="day-head"><h3>Ингредиенты · 1 порция</h3><button class="chip" onclick="editIngredients('${id}')">✎ изменить</button></div><ul class="ingredient-list">${ings.map(x=>`<li>${ingredientText(x)}</li>`).join('')}</ul><p class="tiny-note">Крупы/паста/картофель указаны в готовом виде; мясо и рыба преимущественно в сыром. Значения ориентировочные и зависят от конкретных продуктов.</p></section><section class="section"><h3>Приготовление</h3><p class="note">${esc(r.steps)}</p></section><section class="section"><h3>Хранение и заготовка</h3><p class="note">${esc(r.storage||'Лучше приготовить непосредственно перед едой или хранить по правилам самого скоропортящегося компонента.')}</p></section>${r.replacements?`<section class="section"><h3>Замены</h3><p class="note">${esc(r.replacements)}</p></section>`:''}<div class="row"><button class="btn" onclick="toggleFavorite('${id}')">${state.favorites.includes(id)?'♥ В любимых':'♡ В любимое'}</button><button class="btn secondary" onclick="addToToday('${id}')">Добавить сегодня</button></div>`;modal.classList.remove('hidden')}
function editIngredients(id){const rows=recipeIngredients(id).map(x=>({...x}));window._editingIngredients=rows;const draw=()=>{modalContent.innerHTML=`<h2>Граммовки · ${esc(dish(id).name)}</h2><p class="note">Количество на 1 порцию. Изменения сохраняются только на этом устройстве.</p><div id="ingredientEditor">${window._editingIngredients.map((x,i)=>`<div class="ingredient-edit-row"><input value="${esc(x.name)}" oninput="_editingIngredients[${i}].name=this.value"><input type="number" min="0" step="1" value="${x.qty}" oninput="_editingIngredients[${i}].qty=Number(this.value)"><select onchange="_editingIngredients[${i}].unit=this.value">${['г','мл','шт','ст.л.','ч.л.','банка','уп.'].map(u=>`<option ${x.unit===u?'selected':''}>${u}</option>`).join('')}</select><button class="remove-ing" onclick="_editingIngredients.splice(${i},1);editIngredients('${id}')">×</button></div>`).join('')}</div><div class="week-actions"><button class="btn secondary" onclick="_editingIngredients.push({name:'',qty:0,unit:'г'});editIngredients('${id}')">＋ ингредиент</button><button class="btn" onclick="state.recipeIngredients['${id}']=_editingIngredients.filter(x=>x.name.trim());save();openDish('${id}')">Сохранить</button></div>`};draw()}
function toggleFavorite(id){state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];save();openDish(id)}
function addToToday(id){const d=dish(id),key=d.category==='Завтрак'?'breakfast':d.category==='Перекус'?'snack':'dinner';state.plan[currentDay()]??={};state.plan[currentDay()][key]=id;save();modal.classList.add('hidden');render()}
function renderWeek(){const ts=days.map(day=>totals(slots.map(([k])=>(state.plan[day]||{})[k]).filter(Boolean))),filled=ts.filter(t=>t.kcal>0),avg=filled.length?Math.round(filled.reduce((a,t)=>a+t.kcal,0)/filled.length):0;app.innerHTML=`<section><h2>Неделя</h2><div class="week-actions"><button class="btn" onclick="randomizeWeek()">Составить всю неделю</button><button class="btn secondary" onclick="clearWeek()">Очистить</button></div>${filled.length?`<div class="week-summary">Среднее: <b>${avg} ккал/день</b> · ${filled.length}/7 дней</div>`:''}<p class="note">Нажатие на название блюда открывает рецепт. Для смены есть отдельная кнопка «заменить».</p>${days.map(day=>{const p=state.plan[day]||{},t=totals(slots.map(([k])=>p[k]).filter(Boolean));return `<div class="day"><div class="day-head"><b>${day}</b><span class="meta">${t.kcal} ккал · Б ${t.protein}</span></div><div class="slots">${slots.map(([k,l])=>mealRow(day,k,l)).join('')}</div></div>`}).join('')}</section>`}
function clearWeek(){state.plan={};state.cookingDone={};save();render()}
function chooseMeal(day,key){const desired=key==='breakfast'?'Завтрак':key==='snack'?'Перекус':'Основное';const arr=DISHES.filter(d=>d.category===desired||(key!=='breakfast'&&key!=='snack'&&d.category==='Аварийное'));const draw=q=>arr.filter(d=>(d.name+' '+d.ingredients.join(' ')).toLowerCase().includes(q.toLowerCase())).map(d=>`<div class="card dish-card picker-row"><button class="picker-info" onclick="openDish('${d.id}')"><div class="dish-title">${esc(d.name)}</div><div class="meta">${d.kcal} ккал · Б ${d.protein}</div></button><button class="pick-btn" onclick="setMeal('${day}','${key}','${d.id}')">выбрать</button></div>`).join('');modalContent.innerHTML=`<h2>Выбрать: ${slots.find(s=>s[0]===key)[1]}</h2><input class="search" id="pickerSearch" placeholder="Поиск"><div id="pickerList">${draw('')}</div>`;modal.classList.remove('hidden');document.querySelector('#pickerSearch').oninput=e=>document.querySelector('#pickerList').innerHTML=draw(e.target.value)}
function setMeal(day,key,id){state.plan[day]??={};state.plan[day][key]=id;state.cookingDone={};save();modal.classList.add('hidden');render()}
function randomizeDay(day){const b=DISHES.filter(d=>d.category==='Завтрак'),m=DISHES.filter(d=>d.category==='Основное'),sn=DISHES.filter(d=>d.category==='Перекус');let best,bestScore=1e9;for(let i=0;i<600;i++){const p={breakfast:b[Math.random()*b.length|0].id,lunch:m[Math.random()*m.length|0].id,snack:sn[Math.random()*sn.length|0].id,dinner:m[Math.random()*m.length|0].id},t=totals(Object.values(p)),score=Math.abs(t.kcal-target.kcal)*1.2+Math.abs(t.protein-target.protein)*4+(p.lunch===p.dinner?150:0);if(score<bestScore){bestScore=score;best=p}}state.plan[day]=best;state.cookingDone={};save();render()}
function randomizeWeek(){const usage={},b=DISHES.filter(d=>d.category==='Завтрак'),m=DISHES.filter(d=>d.category==='Основное'),sn=DISHES.filter(d=>d.category==='Перекус');const choose=()=>{let best,bestScore=1e9;for(let i=0;i<900;i++){const p={breakfast:b[Math.random()*b.length|0].id,lunch:m[Math.random()*m.length|0].id,snack:sn[Math.random()*sn.length|0].id,dinner:m[Math.random()*m.length|0].id},t=totals(Object.values(p)),repeat=Object.values(p).reduce((a,id)=>a+(usage[id]||0)*45,0),score=Math.abs(t.kcal-target.kcal)*1.2+Math.abs(t.protein-target.protein)*4+repeat+(p.lunch===p.dinner?180:0);if(score<bestScore){bestScore=score;best=p}}return best};days.forEach(day=>{const p=choose();state.plan[day]=p;Object.values(p).forEach(id=>usage[id]=(usage[id]||0)+1)});state.cookingDone={};save();render()}
function shoppingItems(){const exact=new Map();Object.values(state.plan).forEach(p=>Object.values(p).forEach(id=>{if(!id)return;recipeIngredients(id).forEach(x=>{const key=`${x.name}|${x.unit||'г'}`;exact.set(key,(exact.get(key)||0)+Number(x.qty||0))})}));return [...exact.entries()].map(([key,qty])=>{const [name,unit]=key.split('|');return{name,unit,qty}}).filter(x=>x.qty>0).sort((a,b)=>a.name.localeCompare(b.name,'ru'))}
function renderShopping(){const items=shoppingItems();app.innerHTML=`<section><h2>Покупки</h2><p class="note">Количество суммируется из граммовок всех блюд выбранной недели.</p>${items.map(x=>{const key=`${x.name}|${x.unit}`;return `<label class="shop-row ${state.shopping[key]?'done':''}"><input type="checkbox" ${state.shopping[key]?'checked':''} onchange="toggleShop('${key.replace(/'/g,"\\'")}')"><span>${esc(x.name)} <b>${Math.round(x.qty*10)/10} ${x.unit}</b></span></label>`}).join('')||'<div class="empty">Сначала составьте меню.</div>'}</section>`}
function toggleShop(k){state.shopping[k]=!state.shopping[k];save();renderShopping()}
function weeklyDishCounts(){const map=new Map();days.forEach((day,di)=>{const p=state.plan[day]||{};slots.forEach(([k])=>{const id=p[k];if(id){const x=map.get(id)||{id,count:0,days:[]};x.count++;x.days.push(di);map.set(id,x)}})});return [...map.values()]}
function cookingPlan(){const counts=weeklyDishCounts();if(!counts.length)return[];const groups=[{title:'Воскресенье · основная заготовка',time:'около 90–120 мин',items:[]},{title:'Среда · обновить запасы',time:'около 30–45 мин',items:[]},{title:'Каждый день · свежая сборка',time:'5–20 мин по необходимости',items:[]}];counts.forEach(x=>{const d=dish(x.id),r=RECIPE_DETAILS[x.id],label=`${d.name} × ${x.count}`;if(r.prepType==='batch')groups[0].items.push({id:x.id,label,text:r.steps});else if(r.prepType==='daybefore')groups[2].items.push({id:x.id,label,text:'Подготовить вечером накануне. '+r.steps});else if(r.prepType==='nocook')groups[2].items.push({id:x.id,label,text:'Только собрать перед едой. '+r.steps});else {const late=x.days.some(n=>n>=3);groups[late?1:2].items.push({id:x.id,label,text:r.steps})}});return groups.filter(g=>g.items.length)}
function renderCooking(){const groups=cookingPlan();app.innerHTML=`<section><h2>Готовка</h2><p class="note">План строится автоматически из текущего меню. Основную batch-готовку делаем разом, рыбу и свежие блюда переносим ближе к дню употребления.</p>${groups.length?groups.map((g,gi)=>`<div class="cook-block"><div class="day-head"><h3>${g.title}</h3><span class="meta">${g.time}</span></div>${g.items.map((x,i)=>{const key=`${gi}-${x.id}`;return `<label class="cook-task ${state.cookingDone[key]?'done':''}"><input type="checkbox" ${state.cookingDone[key]?'checked':''} onchange="toggleCook('${key}')"><span><b onclick="event.preventDefault();openDish('${x.id}')">${esc(x.label)}</b><small>${esc(x.text)}</small></span></label>`}).join('')}</div>`).join(''):'<div class="empty">Сначала составьте меню на неделю.</div>'}</section>`}
function toggleCook(k){state.cookingDone[k]=!state.cookingDone[k];save();renderCooking()}
function render(){document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));({today:renderToday,library:renderLibrary,week:renderWeek,cooking:renderCooking,shopping:renderShopping}[state.view]||renderToday)()}
document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;save();render()});document.querySelector('#closeModal').onclick=()=>modal.classList.add('hidden');modal.onclick=e=>{if(e.target===modal)modal.classList.add('hidden')};
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;document.querySelector('#installBtn').classList.remove('hidden')});document.querySelector('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render();
